spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB

server:
  tomcat:
    connection-timeout: 300000  # 5 minutes


ffmpeg:
  path: C:\\ffmpeg-7.1.1-full_build\\bin\\ffmpeg.exe
  probePath: C:\\ffmpeg-7.1.1-full_build\\bin\\ffprobe.exe
  ytDlpPath: D:\yt-dlp.exe

#video:
#  input:
#    path: C:\Users\ShubhamPawar\Downloads\Chup.mp4
#  output:
#    folder: C:\Users\ShubhamPawar\Desktop\videos

datasource:
  url: jdbc:postgresql://localhost:5432/videotrim
  username: postgres
  password: root
  driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Optional: Turn off auto-config exclude if previously used
  autoconfigure:
    exclude: []

